-- A record of every report an organiser has actually taken.
--
-- The reports screen wants "Date Generated" and "Generated By", and there
-- was nothing behind either. The choice was to invent an archive or to
-- start keeping one; this keeps one. A row is written when a report is
-- exported, so the history fills with things that really happened rather
-- than a list that looks busy on day one.
--
-- No file is stored. The export is generated from live data each time it
-- is asked for, which means a report downloaded twice a week apart says
-- two different true things rather than one stale one. Storing the bytes
-- would freeze a number that the gate is still changing.

create table if not exists report_runs (
  id           uuid primary key default gen_random_uuid(),
  event_id     uuid not null references events(id) on delete cascade,
  kind         text not null,           -- guests | rsvp | checkin | seating | performance
  format       text not null,           -- csv
  generated_by uuid references users(id) on delete set null,
  generated_at timestamptz not null default now(),
  row_count    int
);

create index if not exists report_runs_event_idx
  on report_runs (event_id, generated_at desc);

alter table report_runs enable row level security;

grant select, insert on report_runs to app_rw;

-- Same rule as everything else an organiser owns: theirs, through the
-- workspace. app_usher and app_public have no business here at all.
create policy rr_manage on report_runs for all to app_rw
  using (app_manages_event(event_id))
  with check (app_manages_event(event_id));
