// Cross-language interop: a token issued by the SERVER (checkin-core,
// Node) must verify byte-for-byte on the DEVICE (this port). This vector
// was generated by packages/checkin-core/src/token.ts with a fixed key —
// it is a QR code issued by the API being scanned by the phone.
//
// If this test breaks, the two ports have drifted and every pass in the
// field is at risk. Do not update the vector to make it pass; find the
// drift.
import 'package:flutter_test/flutter_test.dart';
import 'package:scanner/core/token.dart';

void main() {
  final key = List<int>.generate(32, (i) => i); // 000102…1f, as on the TS side

  const vector =
      'obLD1OX2SnuMnQ4fKjtMXQ.8OHSw7SlSWiHdmVUQzIhEA.3.w3Kv-3xWn0eUPiva';
  const passId = 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d';
  const eventId = 'f0e1d2c3-b4a5-4968-8776-655443322110';

  test('a token issued by the Node server verifies in Dart', () {
    final v = verifyToken(vector, [
      EventKey(eventId: eventId, eventName: 'X', tokenVersion: 3, key: key),
    ]);
    expect(v.ok, isTrue);
    final ok = v as VerifyOk;
    expect(ok.payload.passId, passId);
    expect(ok.payload.eventId, eventId);
    expect(ok.payload.tokenVersion, 3);
  });

  test('Dart issues the identical token for the identical payload', () {
    final t = issueToken(
      const TokenPayload(passId: passId, eventId: eventId, tokenVersion: 3),
      key,
    );
    expect(t, vector);
  });
}
